---
- hostname:
    name: "{{ ansible_hostname }}"

- name: Creates Application directories
  file: path=/home/{{ common.app_user }}/{{ item }} state=directory owner={{ common.app_user }} group={{ common.app_user }}
  with_items:
    - conf
    - logs
    - www

- name: Crontabs for Auto-Zip Logs
  template: src=crontab.txt dest=/etc/crontab mode=755

# Installation
# - include_role:
#     name: install_supervisor
# - include_role:
#     name: install_nginx

- name: Supervisor config for Nginx
  template: src=supervisor-nginx.conf dest=/etc/supervisord.d/nginx.conf

# CONFIG Deployment
- include: deploy_configs.yml
  when: tomcat.deploy_configs == "true"

# TOMCAT
# - include_role:
#     name: install_tomcat
#   when: tomcat.fresh_install == "true"

- name: Clean the Tomcat Location First
  shell: "rm -rf {{ tomcat.api.install_location }}"

- name: Move Folder Tomcat Fresh Install to the Application Install Location
  shell: "mv -f {{ tomcat.install_location }} {{ tomcat.api.install_location }}"

- name: Edits Tomcat HTTP Port
  become: true
  lineinfile:
    dest: "{{ tomcat.api.install_location }}/conf/server.xml"
    regexp: Connector port="8080" protocol="HTTP/1.1"
    line: <Connector port="{{ tomcat.api.port }}" protocol="HTTP/1.1"

- name: Tuning Tomcat SHUTDOWN Port
  become: true
  lineinfile:
    dest: "{{ tomcat.api.install_location }}/conf/server.xml"
    regexp: <Server port="8005" shutdown="SHUTDOWN">
    line: <Server port="{{ tomcat.api.port + 50 }}" shutdown="SHUTDOWN">

- name: Tuning Tomcat AJP Connector Port
  become: true
  lineinfile:
    dest: "{{ tomcat.api.install_location }}/conf/server.xml"
    regexp: <Connector port="8009" protocol="AJP/1.3" redirectPort="8443" />
    line: <Connector port="{{ tomcat.api.port + 100 }}" protocol="AJP/1.3" redirectPort="{{ tomcat.api.port + 200 }}" />

- name: Supervisor config for Tomcat
  template: src=supervisor-tomcat.conf dest=/etc/supervisord.d/{{ tomcat.api.supervisorctl_name }}.conf
  notify:
    - supervisorctl reread
    - supervisorctl update

- include: deployment.yml
  when: tomcat.api.deployment == "true"
  notify: "killall nginx"
